version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EMOJI-ESCAPE-API
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: EMOJI-ESCAPE-DB
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: EMOJI-ESCAPE-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - laravel_network
    depends_on:
      - db

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local